# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.game_service_pb2 as game__service__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in game_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateGame = channel.unary_unary(
                '/GameService/CreateGame',
                request_serializer=game__service__pb2.GameFormat.SerializeToString,
                response_deserializer=game__service__pb2.GameResponse.FromString,
                _registered_method=True)
        self.AvailableGames = channel.unary_unary(
                '/GameService/AvailableGames',
                request_serializer=game__service__pb2.Empty.SerializeToString,
                response_deserializer=game__service__pb2.GameList.FromString,
                _registered_method=True)
        self.StartGame = channel.unary_unary(
                '/GameService/StartGame',
                request_serializer=game__service__pb2.GameRequest.SerializeToString,
                response_deserializer=game__service__pb2.GameMessage.FromString,
                _registered_method=True)
        self.GetPlayerField = channel.unary_unary(
                '/GameService/GetPlayerField',
                request_serializer=game__service__pb2.PlayerRequest.SerializeToString,
                response_deserializer=game__service__pb2.PlayerFieldResponse.FromString,
                _registered_method=True)
        self.PlaceShips = channel.unary_unary(
                '/GameService/PlaceShips',
                request_serializer=game__service__pb2.PlaceShipsRequest.SerializeToString,
                response_deserializer=game__service__pb2.GameMessage.FromString,
                _registered_method=True)
        self.Attack = channel.unary_unary(
                '/GameService/Attack',
                request_serializer=game__service__pb2.AttackRequest.SerializeToString,
                response_deserializer=game__service__pb2.AttackResponse.FromString,
                _registered_method=True)


class GameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AvailableGames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayerField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceShips(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Attack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGame,
                    request_deserializer=game__service__pb2.GameFormat.FromString,
                    response_serializer=game__service__pb2.GameResponse.SerializeToString,
            ),
            'AvailableGames': grpc.unary_unary_rpc_method_handler(
                    servicer.AvailableGames,
                    request_deserializer=game__service__pb2.Empty.FromString,
                    response_serializer=game__service__pb2.GameList.SerializeToString,
            ),
            'StartGame': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGame,
                    request_deserializer=game__service__pb2.GameRequest.FromString,
                    response_serializer=game__service__pb2.GameMessage.SerializeToString,
            ),
            'GetPlayerField': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerField,
                    request_deserializer=game__service__pb2.PlayerRequest.FromString,
                    response_serializer=game__service__pb2.PlayerFieldResponse.SerializeToString,
            ),
            'PlaceShips': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceShips,
                    request_deserializer=game__service__pb2.PlaceShipsRequest.FromString,
                    response_serializer=game__service__pb2.GameMessage.SerializeToString,
            ),
            'Attack': grpc.unary_unary_rpc_method_handler(
                    servicer.Attack,
                    request_deserializer=game__service__pb2.AttackRequest.FromString,
                    response_serializer=game__service__pb2.AttackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GameService/CreateGame',
            game__service__pb2.GameFormat.SerializeToString,
            game__service__pb2.GameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AvailableGames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GameService/AvailableGames',
            game__service__pb2.Empty.SerializeToString,
            game__service__pb2.GameList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GameService/StartGame',
            game__service__pb2.GameRequest.SerializeToString,
            game__service__pb2.GameMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlayerField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GameService/GetPlayerField',
            game__service__pb2.PlayerRequest.SerializeToString,
            game__service__pb2.PlayerFieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceShips(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GameService/PlaceShips',
            game__service__pb2.PlaceShipsRequest.SerializeToString,
            game__service__pb2.GameMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Attack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GameService/Attack',
            game__service__pb2.AttackRequest.SerializeToString,
            game__service__pb2.AttackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
