# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'game_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12game_service.proto\"\x07\n\x05\x45mpty\"\x1c\n\nGameFormat\x12\x0e\n\x06\x66ormat\x18\x01 \x01(\t\"\x1f\n\x0cGameResponse\x12\x0f\n\x07game_id\x18\x01 \x01(\t\"\x19\n\x08GameList\x12\r\n\x05games\x18\x01 \x03(\t\".\n\x0bGameRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\"\x1e\n\x0bGameMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"0\n\rPlayerRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x0e\n\x06player\x18\x02 \x01(\t\"+\n\x13PlayerFieldResponse\x12\x14\n\x05ships\x18\x01 \x03(\x0b\x32\x05.Ship\" \n\x04Ship\x12\x0b\n\x03row\x18\x01 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x02 \x01(\x05\"\x1d\n\x05Ships\x12\x14\n\x05ships\x18\x01 \x03(\x0b\x32\x05.Ship\"K\n\x11PlaceShipsRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x0e\n\x06player\x18\x02 \x01(\t\x12\x15\n\x05ships\x18\x03 \x01(\x0b\x32\x06.Ships\"J\n\rAttackRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x0e\n\x06player\x18\x02 \x01(\t\x12\x0b\n\x03row\x18\x03 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x04 \x01(\x05\"\x8e\x01\n\x0e\x41ttackResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07victory\x18\x02 \x01(\x08\x12\x0e\n\x06winner\x18\x03 \x01(\t\x12\x0b\n\x03row\x18\x04 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x05 \x01(\x05\x12\x0e\n\x06\x61i_row\x18\x06 \x01(\x05\x12\x0e\n\x06\x61i_col\x18\x07 \x01(\x05\x12\x11\n\tai_result\x18\x08 \x01(\t2\x98\x02\n\x0bGameService\x12(\n\nCreateGame\x12\x0b.GameFormat\x1a\r.GameResponse\x12#\n\x0e\x41vailableGames\x12\x06.Empty\x1a\t.GameList\x12\'\n\tStartGame\x12\x0c.GameRequest\x1a\x0c.GameMessage\x12\x36\n\x0eGetPlayerField\x12\x0e.PlayerRequest\x1a\x14.PlayerFieldResponse\x12.\n\nPlaceShips\x12\x12.PlaceShipsRequest\x1a\x0c.GameMessage\x12)\n\x06\x41ttack\x12\x0e.AttackRequest\x1a\x0f.AttackResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_GAMEFORMAT']._serialized_start=31
  _globals['_GAMEFORMAT']._serialized_end=59
  _globals['_GAMERESPONSE']._serialized_start=61
  _globals['_GAMERESPONSE']._serialized_end=92
  _globals['_GAMELIST']._serialized_start=94
  _globals['_GAMELIST']._serialized_end=119
  _globals['_GAMEREQUEST']._serialized_start=121
  _globals['_GAMEREQUEST']._serialized_end=167
  _globals['_GAMEMESSAGE']._serialized_start=169
  _globals['_GAMEMESSAGE']._serialized_end=199
  _globals['_PLAYERREQUEST']._serialized_start=201
  _globals['_PLAYERREQUEST']._serialized_end=249
  _globals['_PLAYERFIELDRESPONSE']._serialized_start=251
  _globals['_PLAYERFIELDRESPONSE']._serialized_end=294
  _globals['_SHIP']._serialized_start=296
  _globals['_SHIP']._serialized_end=328
  _globals['_SHIPS']._serialized_start=330
  _globals['_SHIPS']._serialized_end=359
  _globals['_PLACESHIPSREQUEST']._serialized_start=361
  _globals['_PLACESHIPSREQUEST']._serialized_end=436
  _globals['_ATTACKREQUEST']._serialized_start=438
  _globals['_ATTACKREQUEST']._serialized_end=512
  _globals['_ATTACKRESPONSE']._serialized_start=515
  _globals['_ATTACKRESPONSE']._serialized_end=657
  _globals['_GAMESERVICE']._serialized_start=660
  _globals['_GAMESERVICE']._serialized_end=940
# @@protoc_insertion_point(module_scope)
